Codeunit 50011 "For FSN"
{
    trigger OnRun()
    begin
        Clear(MailList);
        Clear(CCMailList);
        Clear(BCCMailList);
        Clear(FileName1);
        Clear(FileName);
        Clear(StartingDate);
        Clear(EndingDate);
        Clear(Email);
        Clear(EmailMessage);
        Clear(EmailID);
        Clear(ActualTO);
        Clear(ActualCC);
        CompInfo.Get;
        //SSD SMTPMailSetup.Get;
        //SSD SMTPMailSetup.TestField("User ID");
        //path := 'C:\New folder2';
        FileName1:='FSN Report'; // + '.xlsx';//DELCHR('dd','=','!@#$%^&*()_+}|{":?><,./;[]\=-')+'.PDF';
        EndingDate:=CalcDate('<CM-1M>', Today);
        StartingDate:=CalcDate('<CM-4M+1D>', EndingDate);
        SrNo:=1;
        //SSD Clear(SMTPMail);
        JobQueueEntry.Reset;
        JobQueueEntry.SetRange("Object ID to Run", 50011);
        if JobQueueEntry.FindFirst then JObQueueStateDate:=Dt2Date(JobQueueEntry."Earliest Start Date/Time");
        I:=Date2dmy(JObQueueStateDate, 1);
        if I = 10 then begin
            if EnvironmentInformation.IsProduction()then begin
                MailList.Add('ptomar@zavenir.com');
                CCMailList.Add('ithelpdesk@zavenir.com');
                EmailMessage.Create(MailList, StrSubstNo(SubjectMSG, Format(StartingDate), Format(EndingDate)), '', true, CCMailList, BCCMailList);
            end
            else
            begin
                Clear(MailList);
                Clear(CCMailList);
                //MailList.Add('sunil@ssdynamics.co.in');
                //MailList.Add('hyadav@zavenir.com');
                MailList.Add('ykuntal@zavenir.com');
            end;
            //SSD_Remove
            // ActualTO := 'ptomar@zavenir.com';
            //ActualCC := 'ithelpdesk@zavenir.com';
            //SSD_Remove
            //SMTPMail.AddCC('vraj@alletec.com');
            EmailMessage.AppendToBody(Text50000);
            EmailMessage.AppendToBody(Text60004);
            EmailMessage.AppendToBody(Text60005);
            EmailMessage.AppendToBody(Text60006);
            EmailMessage.AppendToBody(Text50002);
            EmailMessage.AppendToBody(Text60011);
            EmailMessage.AppendToBody(Text60004);
            EmailMessage.AppendToBody(Text60005);
            EmailMessage.AppendToBody(Text60006);
            EmailMessage.AppendToBody(Text60011);
            EmailMessage.AppendToBody(Text50024 + Text50039 + Text60003);
            EmailMessage.AppendToBody(Text60004);
            EmailMessage.AppendToBody(Text60005);
            EmailMessage.AppendToBody(Text60006);
            EmailMessage.AppendToBody(Text60011);
            EmailMessage.AppendToBody(CompInfo.Name);
            //SSD_Remove
            //EmailMessage.AppendToBody(StrSubstNo(ActualID, ActualTO, ActualCC));
            //SSD_Remove
            Clear(TempBlob);
            Clear(Base64Txt);
            TempBlob.CreateOutStream(OutStream);
            CLEAR(FSNReport);
            Item2.Reset;
            //Item.CALCFIELDS("Date Filter");
            Item2.SetRange("Date Filter", StartingDate, EndingDate);
            if Item2.FindFirst then begin
                FSNReport.SetTableview(Item2);
                FSNReport.SaveAs('', ReportFormat::Pdf, OutStream);
                TempBlob.CreateInStream(InStream);
                Base64Txt:=Base64Convert.ToBase64(InStream, true);
                EmailMessage.AddAttachment(FileName + '.pdf', 'application/pdf', Base64Txt);
            end;
            //SMTPMail.AddAttachment(FileName,FileName);
            //SMTPMail.AddAttachment(FileName1, FileName1);
            //SMTPMail.Send;
            //SSD Comment End
            Email.Enqueue(EmailMessage);
            Message(Text50022);
        end;
    end;
    var StartingDate: Date;
    EndingDate: Date;
    //SSD SMTPMail: Codeunit "SMTP Mail";
    SrNo: Integer;
    RecCust: Record Customer;
    //SSD SMTPMailSetup: Record "SMTP Mail Setup";
    CompInfo: Record "Company Information";
    RecSalesInvLine: Record "Sales Invoice Line";
    RecSalesPur: Record "Salesperson/Purchaser";
    path: Text;
    FileName: Text;
    Item: Record Item;
    //SSDU ConsumptionReport1: Report "Consumption Report1";
    Text50000: label 'Dear Sir,';
    Text50001: label 'Sales Invoice';
    Text50002: label 'PFA,';
    Text50003: label 'This is for your records. Kindly acknowledge the receipt.<br/> <br/> ';
    Text50010: label ' <br/> ';
    Text50011: label 'Customer Code :-  ';
    Text50012: label 'Customer Name :-  ';
    Text50013: label 'Amount to Customer :-  ';
    Text50014: label 'Invoice Date :-  ';
    Text50015: label 'Invoice No :-  ';
    Text50016: label 'Quantity in Carton :-  ';
    Text50017: label 'Transporter Name.:-  ';
    Text50018: label 'Truck No :-  ';
    Text50019: label 'Order Date :-  ';
    Text50020: label 'Order No. :-  ';
    Text50021: label 'System have not PCH e-Mail ID, So Informaiton can not sent to PCH Head';
    "------------------------": label 'MS-PB';
    Text59999: label '<html>';
    Text60000: label '<Table>';
    Text60001: label '<TR Border=4>';
    Text60002: label '<TD  width=200 Align=Left>';
    Text60003: label '</TD>';
    Text60004: label '</TR>';
    Text60005: label '</Table>';
    Text60006: label '</html>';
    Text60007: label '<TD  width=500 Align=Left>';
    Text60008: label '<TD  width=100 Align=Center>';
    Text60009: label '<TD Align=Left>';
    Text60010: label '<TD  width=800 Align=right>';
    Text60011: label '<BR>';
    Text60012: label '<B>';
    Text60013: label '</B>';
    Text60014: label '<TD  width=850 Align=right>';
    Text60015: label '<font size="3"> ';
    Text60016: label '</font>';
    Text50022: label 'Mail Sent Successfully !!!!';
    Text50023: label 'This is to advice that the following shipment is being despatched from our factory as follows.';
    Text50024: label '<TD  width=1000 Align=Left>';
    Text50025: label 'This e-Mail is auto generated from Microsoft Dynamics Navison ERP.';
    Text50026: label '<TR>';
    Text50027: label '<table border="1" width="70%">';
    Text50028: label '<TH>';
    Text50029: label '</TH>';
    Text50030: label '<td width="20%">';
    Text50031: label '<td width="50%">';
    Text50032: label '<FONT SIZE=6 FACE="Sans Serif">';
    Text50033: label 'Dear';
    Text50034: label 'Thank you for your confidence in IRT. Please find enclosed invoice no.  ';
    Text50035: label 'The hard copy has been dispatched to you, Pl confirm once you are in receipt of the same.';
    Text50036: label '.';
    Text50037: label 'Customer No: ';
    Text50038: label 'Name: ';
    Text50039: label 'Warm Regards,';
    Text50040: label 'IRT Invoicing Team';
    Text50041: label '<TD  width=5 Align=Center>';
    Text50042: label ' is ready for dispatch"';
    Text50043: label '.00';
    FileName1: Text;
    FSNReport: Report "FSN Report";
    Item2: Record Item;
    JobQueueEntry: Record "Job Queue Entry";
    JObQueueStateDate: Date;
    I: Integer;
    TempBlob: Codeunit "Temp Blob";
    Email: Codeunit Email;
    EmailMessage: Codeunit "Email Message";
    Base64Convert: Codeunit "Base64 Convert";
    DocNo: Code[20];
    InStream: InStream;
    OutStream: OutStream;
    InStream2: InStream;
    OutStream2: OutStream;
    Base64Txt: Text;
    Base64Txt2: Text;
    MailList: List of[Text];
    CCMailList: List of[Text];
    BCCMailList: List of[Text];
    SubjectMSG: Label 'FSN Report from %1 to %2';
    BodyMsg: Label 'Dear Sir or Madam,<br><br>';
    EmailID: Text;
    EnvironmentInformation: Codeunit "Environment Information";
    ActualID: Label 'Atual Mail - TO Mail - %1, CC Mail - %2';
    ActualTO: Text;
    ActualCC: Text;
}
