codeunit 50029 "Email Mgmt Automatic Order Con"
{
    trigger OnRun()
    begin
        MailSendAutoOrderConfirmation();
    end;
    var SalesHeader3: Record "Sales Header";
    Text50010: TextConst ENU = '<br/>', DAN = '<br/>';
    Text59999: TextConst ENU = '<html>', DAN = '<html>';
    Text60000: TextConst ENU = '<Table>', DAN = '<Table>';
    Text60001: TextConst ENU = '<TR Border=4>', DAN = '<TR Border=4>';
    Text60002: TextConst ENU = '<TD  width=200 Align=Left>', DAN = '<TD  width=200 Align=Left>';
    Text60003: TextConst ENU = '</TD>', DAN = '</TD>';
    Text60004: TextConst ENU = '</TR>', DAN = '</TR>';
    Text60005: TextConst ENU = '</Table>', DAN = '</Table>';
    Text60006: TextConst ENU = '</html>', DAN = '</html>';
    Text60007: TextConst ENU = '<TD  width=500 Align=Left>', DAN = '<TD  width=500 Align=Left>';
    Text60008: TextConst ENU = '<TD  width=100 Align=Center>', DAN = '<TD  width=100 Align=Center>';
    Text60009: TextConst ENU = ' <TD Align=Left>', DAN = ' <TD Align=Left>';
    Text60010: TextConst ENU = '<TD  width=800 Align=right>', DAN = '<TD  width=800 Align=right>';
    Text60011: TextConst ENU = '<BR>', DAN = '<BR>';
    Text60012: TextConst ENU = '<B>', DAN = '<B>';
    Text60013: TextConst ENU = '</B>', DAN = '</B>';
    Text60014: TextConst ENU = '<TD  width=850 Align=right>', DAN = '<TD  width=850 Align=right>';
    Text60015: TextConst ENU = '<font size="3"> ', DAN = '<font size="3"> ';
    Text60016: TextConst ENU = '</font>', DAN = '</font>';
    Text50022: TextConst ENU = 'Mail Sent Successfully !!!!', DAN = 'Mail Sent Successfully !!!!';
    Text50023: TextConst ENU = 'This is to advice that the following shipment is being despatched from our factory as follows.', DAN = 'This is to advice that the following shipment is being despatched from our factory as follows.';
    Text50024: TextConst ENU = '<TD  width=1000 Align=Left>', DAN = '<TD  width=1000 Align=Left>';
    //Text50025: TextConst  ENU = '<br/>', DAN = '<br/>' '';
    Text50026: TextConst ENU = ' <TR>', DAN = ' <TR>';
    Text50027: TextConst ENU = '<table border="1" width="70%">', DAN = '<table border="1" width="70%">';
    Text50028: TextConst ENU = '<TH>', DAN = '<TH>';
    Text50029: TextConst ENU = '</TH>', DAN = '</TH>';
    Text50030: TextConst ENU = '<td width="20%">', DAN = '<td width="20%">';
    Text50031: TextConst ENU = '<td width="50%">', DAN = '<td width="50%">';
    Text50032: TextConst ENU = '<FONT SIZE=6 FACE="Sans Serif">', DAN = '<FONT SIZE=6 FACE="Sans Serif">';
    Text50041: TextConst ENU = '<TD  width=.5 Align=Center>', DAN = '<TD  width=.5 Align=Center>';
    Text50042: TextConst ENU = 'Thank for your valuable order', DAN = 'Thank for your valuable order';
    Text50043: TextConst ENU = ' (', DAN = ' (';
    Text50044: TextConst ENU = ')', DAN = ')';
    procedure MailSendAutoOrderConfirmation()
    var
        TempBlob: Codeunit "Temp Blob";
        Email: Codeunit Email;
        EmailMessage: Codeunit "Email Message";
        Base64Convert: Codeunit "Base64 Convert";
        DocNo: Code[20];
        InStream: InStream;
        OutStream: OutStream;
        InStream2: InStream;
        OutStream2: OutStream;
        Base64Txt: Text;
        Base64Txt2: Text;
        MailList: List of[Text];
        CCList: List of[Text];
        SubjectMSG: Label 'Order Acknowledgement Details %1 %2 Customer PO No. %3';
        BodyMsg: Label 'Dear Sir or Madam,<br><br>';
        EmailId: Text;
        UserEmail: Text;
        UserSetup: Record "User Setup";
        RecSalesPerson: Record "Salesperson/Purchaser";
        SalesPersonEmail: Text;
        SPName: Text;
        SPPhNo: Code[21];
        SPEmail: Text;
        SHArchive: Record "Sales Header Archive";
        SalesLine: Record "Sales Line";
        RevisionNo: Text;
        AddCC1: Text;
        RecRef: RecordRef;
        BCCList: List of[Text];
        SalesHeader2: Record "Sales Header";
        OrderConfirmReport: Report "Order Confirmation New";
        EnvironmentInformation: Codeunit "Environment Information";
        ActualID: Label 'Atual Mail - TO Mail - %1, CC Mail - %2';
        ActualTO: Text;
        ActualCC: Text;
        FileName: Text[1024];
        SalesHeader3: Record "Sales Header";
    begin
        SalesHeader2.Reset();
        SalesHeader2.SETRANGE("Document Type", SalesHeader2."Document Type"::Order);
        SalesHeader2.SETRANGE(Status, SalesHeader2.Status::Released);
        SalesHeader2.SetRange("Order Confirmation Mail Send", false);
        SalesHeader2.SetRange("Document Subtype", SalesHeader2."Document Subtype"::Order);
        SalesHeader2.SETFILTER("Posting Date", '>=%1', 20230728D);
        if SalesHeader2.FindSet()then repeat Clear(MailList);
                Clear(CCList);
                Clear(BCCList);
                Clear(EmailId);
                Clear(AddCC1);
                Clear(SalesPersonEmail);
                Clear(UserEmail);
                Clear(Email);
                Clear(EmailMessage);
                // SalesHeader.SETRANGE(SalesHeader."Document Type", SalesHeader."Document Type");
                // SalesHeader.SETRANGE("No.", SalesHeader."No.");
                // REPORT.SAVEASPDF(205, FileName, SalesHeader);
                // CLEAR(EmailId);
                // CLEAR(UserEmail);
                //SalesHeader.TESTFIELD("Cust EMail");
                IF SalesHeader2."Cust EMail" <> '' THEN EmailId:=SalesHeader2."Cust EMail";
                UserSetup.Reset();
                UserSetup.GET(USERID);
                UserEmail:=UserSetup."E-Mail";
                Clear(SalesPersonEmail);
                Clear(SPEmail);
                Clear(SPName);
                Clear(SPPhNo);
                Clear(AddCC1);
                Clear(RevisionNo);
                RecSalesPerson.Reset();
                IF RecSalesPerson.GET(SalesHeader2."Salesperson Code")THEN begin
                    SalesPersonEmail:=RecSalesPerson."E-Mail";
                    SPName:=RecSalesPerson.Name;
                    SPPhNo:=RecSalesPerson."Phone No.";
                    SPEmail:=RecSalesPerson."E-Mail";
                    IF(RecSalesPerson."Resp. CCare Exe. Email Id" <> '')THEN //Alle 22/07/20
 AddCC1:=RecSalesPerson."Resp. CCare Exe. Email Id";
                end;
                SHArchive.RESET;
                SHArchive.SETRANGE("Document Type", SalesHeader2."Document Type");
                SHArchive.SETRANGE("No.", SalesHeader2."No.");
                IF SHArchive.FINDLAST THEN BEGIN
                    RevisionNo:=' (Rev No.  ' + FORMAT(SHArchive."Version No.") + ')';
                END;
                MailList.AddRange(EmailId.Split(';'));
                if AddCC1 <> '' then CCList.AddRange(AddCC1.Split(';'));
                if SalesPersonEmail <> '' then CCList.AddRange(SalesPersonEmail.Split(';'));
                CCList.add('ccare@zavenir.com');
                CCList.Add('ithelpdesk@zavenir.com');
                ActualTO:=EmailId;
                ActualCC:=AddCC1 + ';' + SalesPersonEmail + ';' + 'ccare@zavenir.com;ithelpdesk@zavenir.com';
                if EnvironmentInformation.IsProduction()then EmailMessage.Create(MailList, StrSubstNo(SubjectMSG, SalesHeader2."No.", RevisionNo, SalesHeader2."External Document No."), '', true, CCList, BCCList)
                else
                begin
                    Clear(MailList);
                    Clear(CCList);
                    //MailList.Add('sunil@ssdynamics.co.in');
                    //MailList.Add('hyadav@zavenir.com');
                    MailList.Add('ykuntal@zavenir.com');
                    EmailMessage.Create(MailList, StrSubstNo(SubjectMSG, SalesHeader2."No.", RevisionNo, SalesHeader2."External Document No."), '', true);
                end;
                //EmailMessage.AppendToBody('ccare@zavenir.com');
                EmailMessage.AppendToBody(BodyMsg);
                EmailMessage.AppendToBody('Please find the attached PDF for Order Acknowledgement.<br><br>');
                EmailMessage.AppendToBody('</TR>');
                EmailMessage.AppendToBody('</Table>');
                EmailMessage.AppendToBody('</html>');
                EmailMessage.AppendToBody('<BR>');
                EmailMessage.AppendToBody('<html>');
                EmailMessage.AppendToBody('<TR Border=4>');
                EmailMessage.AppendToBody('</TR>');
                EmailMessage.AppendToBody('</Table>');
                EmailMessage.AppendToBody('</html>');
                EmailMessage.AppendToBody('</TR>');
                EmailMessage.AppendToBody('</Table>');
                EmailMessage.AppendToBody('</html>');
                EmailMessage.AppendToBody('<BR>');
                EmailMessage.AppendToBody('<table border="1" width="70%">' + '<TR>' + '<td width="20%">' + '<B>' + 'Sales Order No.' + '</B>' + '</TD>');
                EmailMessage.AppendToBody('<td width="20%">' + '<B>' + 'Customer Name' + '</B>' + '</TD>');
                EmailMessage.AppendToBody('<td width="20%">' + '<B>' + 'Description' + '</B>' + '</TD>');
                EmailMessage.AppendToBody('<td width="20%">' + '<B>' + 'Description 2' + '</B>' + '</TD>');
                EmailMessage.AppendToBody('<TD  width=.5 Align=Center>' + '<B>' + 'Quantity' + '</B>' + '</TD>');
                EmailMessage.AppendToBody('</TR>');
                SalesLine.RESET;
                SalesLine.SETRANGE("Document No.", SalesHeader2."No.");
                IF SalesLine.FINDFIRST THEN BEGIN
                    REPEAT EmailMessage.AppendToBody('<TR>' + '<td width="20%">' + FORMAT(SalesHeader2."No.") + '</TD>');
                        EmailMessage.AppendToBody('<td width="20%">' + FORMAT(SalesHeader2."Sell-to Customer Name") + '</TD>');
                        EmailMessage.AppendToBody('<td width="20%">' + FORMAT(SalesLine.Description) + '</TD>');
                        EmailMessage.AppendToBody('<td width="20%">' + FORMAT(SalesLine."Description 2") + '</TD>');
                        EmailMessage.AppendToBody('<TD  width=.5 Align=Center>' + FORMAT(SalesLine.Quantity) + ' </TD>');
                        EmailMessage.AppendToBody('</TR>');
                    UNTIL SalesLine.NEXT = 0;
                END;
                EmailMessage.AppendToBody(Text60004);
                EmailMessage.AppendToBody(Text60005);
                EmailMessage.AppendToBody(Text60006);
                EmailMessage.AppendToBody(Text60011);
                EmailMessage.AppendToBody(Text60004);
                EmailMessage.AppendToBody(Text60005);
                EmailMessage.AppendToBody(Text60006);
                EmailMessage.AppendToBody(Text60011);
                EmailMessage.AppendToBody(Text60004);
                EmailMessage.AppendToBody(Text60005);
                EmailMessage.AppendToBody(Text60006);
                EmailMessage.AppendToBody(Text60011);
                EmailMessage.AppendToBody(Text59999);
                EmailMessage.AppendToBody(Text60000);
                EmailMessage.AppendToBody(Text60001);
                EmailMessage.AppendToBody(Text60004);
                EmailMessage.AppendToBody(Text60005);
                EmailMessage.AppendToBody(Text60006);
                EmailMessage.AppendToBody(Text60011);
                EmailMessage.AppendToBody('If you need any assistance, please contact : <br><br>');
                EmailMessage.AppendToBody('<table border="1" cellpadding="3" style="border-style: solid; border-width: 1px">');
                EmailMessage.AppendToBody('<tr>');
                EmailMessage.AppendToBody('<td><b><font face="arial" size ="2">Sales Person & Contact No.</font></b></td>');
                EmailMessage.AppendToBody('<td><font face="arial" size ="2">' + FORMAT(SPName) + ' ; ' + FORMAT(SPPhNo) + ' ; ' + FORMAT(SPEmail) + '</font></td>');
                EmailMessage.AppendToBody('</tr>');
                EmailMessage.AppendToBody('<tr>');
                EmailMessage.AppendToBody('<td><b><font face="arial" size ="2">CCare Person & Contact No.</font></b></td>');
                EmailMessage.AppendToBody('<td><font face="arial" size ="2">' + FORMAT(RecSalesPerson."Resp. CCare Exe. Name") + ' ; ' + FORMAT(RecSalesPerson."Resp. CCare Exe. Phone No.") + ' ; ' + FORMAT(RecSalesPerson."Resp. CCare Exe. Email Id") + '</font></td>');
                EmailMessage.AppendToBody('</tr>');
                EmailMessage.AppendToBody('</table>');
                EmailMessage.AppendToBody('Thank you for your business. <br><br>');
                EmailMessage.AppendToBody('With Best Regards, <br><br>' + ' <b>Customer Care Team</b> <br><br>');
                EmailMessage.AppendToBody('This is an automated email. Replies to this message are not monitored or answered.</b> <br><br>');
                //SMTPMail.AddAttachment(FileName, FileName);
                //SSD_Remove
                // EmailMessage.AppendToBody(StrSubstNo(ActualID, ActualTO, ActualCC));
                //SSD_Remove
                Clear(TempBlob);
                Clear(Base64Txt);
                Clear(RecRef);
                FileName:='Order Acknowledgement';
                FileName:=DelChr(FileName, '=', '/\-. ');
                TempBlob.CreateOutStream(OutStream);
                SalesHeader3.Get(SalesHeader2."Document Type", SalesHeader2."No.");
                SalesHeader3.SetRecFilter();
                RecRef.GetTable(SalesHeader3);
                RecRef.SetRecFilter();
                if Report.SaveAs(Report::"Order Confirmation New", '', ReportFormat::Pdf, OutStream, RecRef)then begin
                    //OrderConfirmReport.SaveAs('', ReportFormat::Pdf, OutStream);
                    TempBlob.CreateInStream(InStream);
                    Base64Txt:=Base64Convert.ToBase64(InStream, true);
                    EmailMessage.AddAttachment(FileName + '.pdf', 'application/pdf', Base64Txt);
                    Email.Enqueue(EmailMessage);
                //Attchment
                end;
                //IF SMTPMail.TrySend THEN BEGIN
                //SMTPMail.Send();
                SalesHeader2."Order Confirmation Mail Send":=TRUE;
                SalesHeader2.MODIFY;
                SLEEP(200);
                COMMIT;
            until SalesHeader2.Next() = 0;
    //Attchment
    // SalesHeader2.SetRecFilter();
    // RecRef.GetTable(SalesHeader2);
    // RecRef.SetRecFilter();
    END;
}
