Report 50103 "Certificate of Analysis"
{
    // Version       Date(DD/MM/YYYY)           Description
    // BS14122016    14/12/2016                 Specific Gravity - "Posted Quality Order Line"."Inspection Value2" to be printed in 3 digits.
    DefaultLayout = RDLC;
    RDLCLayout = './Layouts/Certificate of Analysis.rdl';
    PreviewMode = PrintLayout;
    UsageCategory = ReportsandAnalysis;
    ApplicationArea = all;

    dataset
    {
        dataitem(ILE1; "Item Ledger Entry")
        {
            DataItemTableView = sorting("Document No.", "Document Type", "Document Line No.")where("Entry Type"=const(Sale));
            RequestFilterFields = "Lot No.";

            column(ReportForNavId_1000000076;1000000076)
            {
            }
            dataitem("Value Entry"; "Value Entry")
            {
                DataItemLink = "Item Ledger Entry No."=field("Entry No.");
                DataItemTableView = sorting("Document No.")where(Adjustment=const(false));
                RequestFilterFields = "Document No.", "Item No.", "Entry No.";

                column(ReportForNavId_1000000060;1000000060)
                {
                }
                column(PageNo; PageNo)
                {
                }
                column(Value_Entry_Entry_No_; "Entry No.")
                {
                }
                column(Value_Entry_Item_Ledger_Entry_No_; "Item Ledger Entry No.")
                {
                }
                dataitem("Item Ledger Entry"; "Item Ledger Entry")
                {
                    DataItemLink = "Entry No."=field("Item Ledger Entry No.");
                    DataItemTableView = sorting("Document No.", "Document Type", "Document Line No.")where("Entry Type"=const(Sale));
                    RequestFilterFields = "Lot No.";

                    column(ReportForNavId_1000000057;1000000057)
                    {
                    }
                    column(Item_Ledger_Entry_Entry_No_; "Entry No.")
                    {
                    }
                    column(Item_Ledger_Entry_Lot_No_; "Lot No.")
                    {
                    }
                    dataitem("Posted Quality Order Header"; "SSD Posted Quality Order Hdr")
                    {
                        DataItemLink = "Lot No."=field("Lot No.");
                        DataItemTableView = sorting("No.");
                        RequestFilterFields = "Source Document No.", "Lot No.";

                        column(ReportForNavId_1000000054;1000000054)
                        {
                        }
                        column(PostingDate_PostedQualityOrderHeader; "Posted Quality Order Header"."Posting Date")
                        {
                        }
                        column(ApprovedDate_PostedQualityOrderHeader; "Posted Quality Order Header"."Approved Date")
                        {
                        }
                        column(ULRNo; "Posted Quality Order Header"."ULR No." + PType)
                        {
                        }
                        column(CompInfo__New_Logo2_; CompInfo."New Logo2")
                        {
                        }
                        column(CompInfo__New_Logo1_; CompInfo."New Logo1")
                        {
                        }
                        column(CompInfo_Name; CompInfo.Name)
                        {
                        }
                        column(Posted_Quality_Order_Header__No__; "No.")
                        {
                        }
                        column(Posted_Quality_Order_Header__Posting_Date_; "Posting Date")
                        {
                        }
                        column(Posted_Quality_Order_Header__Item_No__; "Item No.")
                        {
                        }
                        column(Item_Description_____Item__Description_2_; Item.Description + ' ' + Item."Description 2")
                        {
                        }
                        column(Posted_Quality_Order_Header__Lot_No__; "Lot No.")
                        {
                        }
                        column(FORMAT__Lot_Size_______FORMAT_Item__Base_Unit_of_Measure__; Format("Lot Size") + ' ' + Format(Item."Base Unit of Measure"))
                        {
                        }
                        column(Posted_Quality_Order_Header__Posted_Quality_Order_Header___Posting_Date_; "Posted Quality Order Header"."Posting Date")
                        {
                        }
                        column(DataItem1000000044;'This document is system generated by ' + 'Zavenir' + ' and valid without signature. For any queries, please contact us with the relevant certificate no(s).')
                        {
                        }
                        column(email___CompInfo__E_Mail_________Web___CompInfo__Home_Page_;'email ' + CompInfo."E-Mail" + ' | ' + 'Web ' + CompInfo."Home Page")
                        {
                        }
                        column(IsNABLAccredited_PostedQualityOrderHeader; "Posted Quality Order Header"."Is NABL Accredited")
                        {
                        }
                        column(Certificate_of_AnalysisCaption; Certificate_of_AnalysisCaptionLbl)
                        {
                        }
                        column(Certificate_No_Caption; Certificate_No_CaptionLbl)
                        {
                        }
                        column(Certificate_DateCaption; Certificate_DateCaptionLbl)
                        {
                        }
                        column(Item_CodeCaption; Item_CodeCaptionLbl)
                        {
                        }
                        column(Item_NameCaption; Item_NameCaptionLbl)
                        {
                        }
                        column(Batch_No_Caption; Batch_No_CaptionLbl)
                        {
                        }
                        column(Batch_QuantityCaption; Batch_QuantityCaptionLbl)
                        {
                        }
                        column(Date_of_ManufacturingCaption; Date_of_ManufacturingCaptionLbl)
                        {
                        }
                        column(InsepectionCheck; InsepectionCheck)
                        {
                        }
                        column(IsQualityCheck; IsQualityCheck)
                        {
                        }
                        column(ExpirationDate_ItemLedgerEntry; ExpiryDate)
                        {
                        }
                        column(TestedBy; TestedBy)
                        {
                        }
                        column(Approvedby; Approvedby)
                        {
                        }
                        dataitem("Posted Quality Order Line"; "SSD Posted Quality Order Line")
                        {
                            DataItemLink = "Document No."=field("No.");
                            DataItemTableView = sorting("Document No.", "Line No.")where("Value to be Print"=const(true));

                            column(ReportForNavId_1000000034;1000000034)
                            {
                            }
                            column(Posted_Quality_Order_Line_Description; Description)
                            {
                            }
                            column(QualityMeasurements_Protocol; QualityMeasurements.Protocol)
                            {
                            }
                            column(MinVal; MinVal)
                            {
                            }
                            column(MaxVal; MaxVal)
                            {
                            }
                            column(AverageTestValue; AverageTestValue)
                            {
                            }
                            column(Posted_Quality_Order_Line__Posted_Quality_Order_Line___Unit_of_Measure_Code_; "Posted Quality Order Line"."Unit of Measure Code")
                            {
                            }
                            column(Conforms_to_our_manufacturing_specifications_;'Conforms to our manufacturing specifications')
                            {
                            }
                            column(We_hereby_confirm_that_the_material_under_this_certificate__;'We hereby confirm that the material under this certificate:')
                            {
                            }
                            column(Does_not_conform__but_passed_due_to_insignificance_and___or_validation_of_deviation__;'Does not conform, but passed due to insignificance and / or validation of deviation.')
                            {
                            }
                            column(It_is_further_confirmed_that_the_product_conforms_to_published_data_sheet_and_SDS_;'It is further confirmed that the product conforms to published data sheet and SDS')
                            {
                            }
                            column(Posted_Quality_Order_Header___Is_Coil_Type_; "Posted Quality Order Header"."Is Coil Type")
                            {
                            }
                            column(Posted_Quality_Order_Header___Inspection_Report_Generated_; "Posted Quality Order Header"."Inspection Report Generated")
                            {
                            }
                            column(CutomerNo; CutomerNo)
                            {
                            }
                            column(CutomerName; CutomerName)
                            {
                            }
                            column(OrderNo1; OrderNo1)
                            {
                            }
                            column(CustItemCode; CustItemCode)
                            {
                            }
                            column(InvoiceNo; InvoiceNo)
                            {
                            }
                            column(FORMAT_ABS__Item_Ledger_Entry__Quantity_______FORMAT_Item__Base_Unit_of_Measure__; Format(Abs("Item Ledger Entry".Quantity)) + ' ' + Format(Item."Base Unit of Measure"))
                            {
                            }
                            column(Customer_Name_;'Customer Name')
                            {
                            }
                            column(Ship_to_Name_;'Ship to Name')
                            {
                            }
                            column(Customer_PO_No__;'Customer PO No.')
                            {
                            }
                            column(Invoice_No__;'Invoice No.')
                            {
                            }
                            column(Quantity_Shipped_;'Quantity Shipped')
                            {
                            }
                            column(Customer_Item_Code_;'Customer Item Code')
                            {
                            }
                            column(Test_ParameterCaption; Test_ParameterCaptionLbl)
                            {
                            }
                            column(ProtocolCaption; ProtocolCaptionLbl)
                            {
                            }
                            column(Min_ValueCaption; Min_ValueCaptionLbl)
                            {
                            }
                            column(Max__ValueCaption; Max__ValueCaptionLbl)
                            {
                            }
                            column(Test_ValueCaption; Test_ValueCaptionLbl)
                            {
                            }
                            column(UnitCaption; UnitCaptionLbl)
                            {
                            }
                            column(ConfirmationCaption; ConfirmationCaptionLbl)
                            {
                            }
                            column(Shipping_DataCaption; Shipping_DataCaptionLbl)
                            {
                            }
                            column(Posted_Quality_Order_Line_Document_No_; "Document No.")
                            {
                            }
                            column(Posted_Quality_Order_Line_Line_No_; "Line No.")
                            {
                            }
                            column(Discipline_PostedQualityOrderLine; "Posted Quality Order Line".Discipline)
                            {
                            }
                            column(Group_PostedQualityOrderLine; "Posted Quality Order Line".Group)
                            {
                            }
                            column(Discipline_Caption; Discipline_Caption)
                            {
                            }
                            column(Group_caption; Group_caption)
                            {
                            }
                            trigger OnAfterGetRecord()
                            begin
                                if "Posted Quality Order Line"."Meas. Value Type" = "Posted Quality Order Line"."meas. value type"::Value then begin
                                    //>> BS14122016
                                    //IF (Description = 'Total Acid Number') THEN BEGIN
                                    if(Description = 'Total Acid Number') or FindSpecificGravityInDescrition(Description)then begin
                                        //<< BS14122016
                                        ThreeDecPlace:=Format("Posted Quality Order Line"."Inspection Value2");
                                        Len:=StrLen(ThreeDecPlace);
                                        Position:=StrPos(ThreeDecPlace, '.');
                                        i:=Len - Position;
                                        if(i = 1)then AverageTestValue:=Format(ThreeDecPlace) + '00';
                                        if(i = 2)then AverageTestValue:=Format(ThreeDecPlace) + '0';
                                        if(i = 3)then AverageTestValue:=Format(ThreeDecPlace);
                                        if(i > 3)then AverageTestValue:=Format(ROUND("Posted Quality Order Line"."Inspection Value2", 0.001));
                                    end
                                    else
                                        AverageTestValue:=Format("Posted Quality Order Line"."Inspection Value2");
                                end
                                else
                                begin
                                    if "Posted Quality Order Line"."Quality Pass" then AverageTestValue:='PASS'
                                    else
                                        AverageTestValue:='NOT PASS' end;
                                if "Posted Quality Order Line"."Minimum Value" <> 0 then MinVal:=Format("Posted Quality Order Line"."Minimum Value")
                                else
                                    MinVal:='-';
                                if "Posted Quality Order Line"."Maximum Value" <> 0 then MaxVal:=Format("Posted Quality Order Line"."Maximum Value")
                                else
                                    MaxVal:='-';
                                QualityMeasurements.Reset;
                                if QualityMeasurements.Get("Posted Quality Order Line"."Meas. Code")then;
                                if QualityMeasurements.Protocol = 'Measurement' then AverageTestValue:=Format(ROUND("Posted Quality Order Line"."Inspection Value2", 0.01));
                                //message('%1',QualityMeasurements.Protocol);
                                //ALLE-NM 220619 >>
                                if "Posted Quality Order Line"."Meas. Value Type" = "Posted Quality Order Line"."meas. value type"::Value then begin
                                    if((Description <> 'Total Acid Number') or (FindSpecificGravityInDescrition(Description) = false)) and (QualityMeasurements.Protocol <> 'Measurement')then begin
                                        QualityMeasureRec.Reset;
                                        QualityMeasureRec.SetRange(Code, "Posted Quality Order Line"."Meas. Code");
                                        if QualityMeasureRec.FindFirst then begin
                                            if QualityMeasureRec."0D Para" then AverageTestValue:=Format(ROUND("Posted Quality Order Line"."Inspection Value2", 1))
                                            else if QualityMeasureRec."1D Para" then AverageTestValue:=Format(ROUND("Posted Quality Order Line"."Inspection Value2", 0.1))
                                                else if QualityMeasureRec."2D Para" then AverageTestValue:=Format(ROUND("Posted Quality Order Line"."Inspection Value2", 0.01))
                                                    else if QualityMeasureRec."3D Para" then AverageTestValue:=Format(ROUND("Posted Quality Order Line"."Inspection Value2", 0.001))
                                                        else
                                                            AverageTestValue:=Format(ROUND("Posted Quality Order Line"."Inspection Value2", 0.01))end;
                                    end;
                                end;
                            //ALLE-NM 220619 >>
                            end;
                        }
                        trigger OnAfterGetRecord()
                        begin
                            CustItemCode:='NA';
                            ItemCrossRef.Reset;
                            ItemCrossRef.SetRange(ItemCrossRef."Reference Type", ItemCrossRef."Reference Type"::Customer);
                            ItemCrossRef.SetRange(ItemCrossRef."Reference Type No.", CustNoGbl);
                            ItemCrossRef.SetRange(ItemCrossRef."Item No.", "Posted Quality Order Header"."Item No.");
                            if ItemCrossRef.FindFirst then CustItemCode:=ItemCrossRef."Reference No.";
                            if not "Posted Quality Order Header".Approved then Error('Quality Order has not been Approved, You can not take print.');
                            Item.Reset;
                            if Item.Get("Posted Quality Order Header"."Item No.")then;
                            Vendor.Reset;
                            if Vendor.Get("Posted Quality Order Header"."Source Code")then;
                            IsQualityCheck:='NO';
                            InsepectionCheck:='NO';
                            if "Posted Quality Order Header"."Is Coil Type" then IsQualityCheck:='YES';
                            if "Posted Quality Order Header"."Inspection Report Generated" then InsepectionCheck:='YES';
                            if UserSetup.Get("Posted Quality Order Header"."Posted By")then TestedBy:=UserSetup.Name;
                            if UserSetup.Get("Posted Quality Order Header"."Approved by")then Approvedby:=UserSetup.Name;
                            //ALLE-NM >>
                            Clear(PType);
                            if Database.COMPANYNAME = 'Zavenir Daubert India (P) Ltd.' then PType:=Format("Posted Quality Order Header"."Parameter Type");
                        //ALLE-NM <<
                        end;
                    }
                    trigger OnAfterGetRecord()
                    begin
                        LotNo:="Lot No.";
                        ILE.Reset;
                        ILE.SetRange("Lot No.", "Lot No.");
                        if ILE.FindFirst then ExpiryDate:=ILE."Expiration Date";
                    end;
                }
                trigger OnAfterGetRecord()
                begin
                    CurrReport.PageNo:=1;
                    PageNo:=CurrReport.PageNo;
                end;
            }
        }
    }
    requestpage
    {
        layout
        {
        }
        actions
        {
        }
    }
    labels
    {
    }
    trigger OnPreReport()
    begin
        CompInfo.Get;
        CompInfo.CalcFields(CompInfo.Picture, CompInfo."New Logo1", CompInfo."New Logo2");
    end;
    var CompInfo: Record "Company Information";
    Item: Record Item;
    Vendor: Record Vendor;
    InvoiceNo: Code[20];
    InvoiceDate: Date;
    CutomerNo: Text[80];
    CutomerName: Text[80];
    OrderNo1: Code[50];
    QtyShipped: Decimal;
    AverageTestValue: Text[30];
    MinVal: Text[30];
    MaxVal: Text[30];
    QualityMeasurements: Record "SSD Quality Measurements";
    CustItemCode: Code[20];
    ItemCrossRef: Record "Item Reference";
    CustNoGbl: Code[20];
    Certificate_of_AnalysisCaptionLbl: label 'Certificate of Analysis';
    Certificate_No_CaptionLbl: label 'Certificate No.';
    Certificate_DateCaptionLbl: label 'Certificate Date';
    Item_CodeCaptionLbl: label 'Item Code';
    Item_NameCaptionLbl: label 'Item Name';
    Batch_No_CaptionLbl: label 'Batch No.';
    Batch_QuantityCaptionLbl: label 'Batch Quantity';
    Date_of_ManufacturingCaptionLbl: label 'Date of Manufacturing';
    Test_ParameterCaptionLbl: label 'Test Parameter';
    ProtocolCaptionLbl: label 'Protocol';
    Min_ValueCaptionLbl: label 'Min.Value';
    Max__ValueCaptionLbl: label 'Max. Value';
    Test_ValueCaptionLbl: label 'Test Value';
    UnitCaptionLbl: label 'Unit';
    ConfirmationCaptionLbl: label 'Confirmation';
    Shipping_DataCaptionLbl: label 'Shipping Data';
    IsQualityCheck: Text;
    InsepectionCheck: Text;
    LotNo: Code[20];
    ILE: Record "Item Ledger Entry";
    ExpiryDate: Date;
    ThreeDecPlace: Text;
    Position: Integer;
    NewChar: Text;
    Len: Integer;
    i: Integer;
    Loop: Integer;
    PageNo: Integer;
    TestedBy: Text;
    Approvedby: Text;
    UserSetup: Record "User Setup";
    PType: Text;
    QualityMeasureRec: Record "SSD Quality Measurements";
    Discipline_Caption: label 'Discipline';
    Group_caption: label 'Group';
    procedure SalesInvoice(InvNo: Code[20]; InvDate: Date; OrderNo: Code[35]; CustomerNo: Text[80]; CustomerName: Text[80]; QtyShippedAgainstLot: Decimal; CustNo: Code[20])
    begin
        InvoiceNo:=InvNo;
        InvoiceDate:=InvDate;
        CutomerNo:=CustomerNo;
        CutomerName:=CustomerName;
        OrderNo1:=OrderNo;
        QtyShipped:=QtyShippedAgainstLot;
        CustNoGbl:=CustNo;
    end;
    procedure FindSpecificGravityInDescrition(Des: Text[150]): Boolean var
        SubStrPOs: Integer;
    begin
        // BS14122016 new function added.
        SubStrPOs:=0;
        SubStrPOs:=StrPos(Des, 'Specific Gravity');
        if SubStrPOs > 0 then exit(true)
        else
            exit(false);
    end;
}
